name: flutter_game_framework
description: This module is a derivative of flutter_corelib, created by separating and refactoring its components into a standalone package for better modularity and reusability.
version: 1.0.0
homepage: https://github.com/Glitch9Inc/flutter_game_framework
repository: https://github.com/Glitch9Inc/flutter_game_framework
issue_tracker: https://github.com/Glitch9Inc/flutter_game_framework/issues
documentation: https://github.com/Glitch9Inc/flutter_game_framework#readme
publish_to: "none" # Remove this line to publish to pub.dev

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # for game audio (BGM, SFX, Voice, etc)
  just_audio: ^0.9.39
  dio: ^5.5.0+1

  flutter_corelib: 
    path: ../flutter_corelib

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
